[project]
name = "labot"
version = "0.1.0"
description = "Labot (LAboratory BOT) supports handbook organizing, teaching, research etc."
readme = "README.md"
requires-python = ">=3.10,<3.14"
license = { text = "MIT" }
authors = [{ name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }]
dependencies = [
  "gitpython>=3.1.43,<4.0.0",
  "click>=8.1.7,<9.0.0",
  "pre-commit>=3.2.0,<4.0.0",
  "colrev-sync==0.2.0",
  "docx-mailmerge>=0.5.0,<0.6.0",
  "pygithub>=2.5.0,<3.0.0",
  "python-docx>=1.1.2,<2.0.0",
  "inquirer>=3.4.0,<4.0.0",
  "pandas>=2.2.3,<3.0.0",
  "yamale>=5.2.1,<6.0.0",
  "openai>=1.58.1,<2.0.0",
  "pypdf2>=3.0.1,<4.0.0",
  "colrev>=0.16.0",
  "jinja2>=3.1.5,<4.0.0",
  "exchangelib>=5.5.0,<6.0.0",
  "pdfannots>=0.5,<0.6",
  "language-tool-python>=2.9.4,<3.0.0",
  "questionary>=2.1.1",
]

[tool.setuptools.package-data]
labot = ["data/*.yml"]

[project.scripts]
labot = "labot.cli:main"

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["requests.*", "yaml.*", "pkg_resources.*"]
ignore_missing_imports = true

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
